### ISSUE TITLE
When testing I get this error, how can I fix this?

### ISSUE THREAD

**Issue by abhranil08** [salesforce/densecap#39]
Namespace(attn_dropout=0.2, batch_size=1, cap_dropout=0.2, cfgs_file='cfgs/yc2.yml', cuda=True, d_hidden=2048, d_model=1024, dataset='yc2', dataset_file='./data/yc2/yc2_annotations_trainval.json', densecap_eval_file='./tools/densevid_eval/evaluate.py', densecap_references=['./data/yc2/val_yc2.json'], dur_file='./data/yc2/yc2_duration_frame.csv', feature_root='/checkpoint/luoweizhou/old_checkpoint02/dat/yc2/rgb_motion_1d', gated_mask=False, id='yc2-2L-gt-mask-19', image_feat_size=3072, in_emb_dropout=0.1, kernel_list=[1, 3, 5, 7, 9, 11, 15, 21, 27, 33, 41, 49, 57, 71, 111, 161], learn_mask=False, max_prop_num=500, max_sentence_len=20, min_prop_before_nms=200, min_prop_num=50, n_heads=8, n_layers=2, num_workers=2, pos_thresh=0.7, sampling_sec=0.5, slide_window_size=480, slide_window_stride=20, start_from='./checkpoint/yc2-2L-gt-mask/model_epoch_19.t7', stride_factor=50, val_data_folder='validation', vis_emb_dropout=0.1)

Namespace(attn_dropout=0.2, batch_size=1, cap_dropout=0.2, cfgs_file='cfgs/yc2.yml', cuda=True, d_hidden=2048, d_model=1024, dataset='yc2', dataset_file='./data/yc2/yc2_annotations_trainval.json', densecap_eval_file='./tools/densevid_eval/evaluate.py', densecap_references=['./data/yc2/val_yc2.json'], dur_file='./data/yc2/yc2_duration_frame.csv', feature_root='/checkpoint/luoweizhou/old_checkpoint02/dat/yc2/rgb_motion_1d', gated_mask=False, id='yc2-2L-gt-mask-19', image_feat_size=3072, in_emb_dropout=0.1, kernel_list=[1, 3, 5, 7, 9, 11, 15, 21, 27, 33, 41, 49, 57, 71, 111, 161], learn_mask=False, max_prop_num=500, max_sentence_len=20, min_prop_before_nms=200, min_prop_num=50, n_heads=8, n_layers=2, num_workers=2, pos_thresh=0.7, sampling_sec=0.5, slide_window_size=480, slide_window_stride=20, start_from='./checkpoint/yc2-2L-gt-mask/model_epoch_19.t7', stride_factor=50, val_data_folder='validation', vis_emb_dropout=0.1)
loading dataset
number of words in the vocab: 1011
number of sentences in training: 10337, # of sentences in validation: 3492
number of training videos: 1333
total number of samples (unique videos): 0
total number of sentences: 0
building model
Initializing weights from ./checkpoint/yc2-2L-gt-mask/model_epoch_19.t7
**Traceback (most recent call last):
  File "code.py", line 255, in <module>
    main()
  File "code.py", line 249, in main
    recall_area = validate(model, test_loader, args)
  File "code.py", line 201, in validate
    print("average proposal number: {}".format(avg_prop_num/len(loader.dataset)))
ZeroDivisionError: division by zero**

**This is the python command :** python code.py --cfgs_file cfgs/yc2.yml --densecap_eval_file ./tools/densevid_eval/evaluate.py --batch_size 1 --start_from ./checkpoint/yc2-2L-gt-mask/model_epoch_19.t7 --id yc2-2L-gt-mask-19 --val_data_folder 'validation' --cuda  | tee log/eval-yc2-2L-gt-mask-19

**Comment by abhranil08** [comment]
Solved the above one.
Now getting this error.


`
Namespace(attn_dropout=0.2, batch_size=1, cap_dropout=0.2, cfgs_file='cfgs/yc2.yml', cuda=True, d_hidden=2048, d_model=1024, dataset='yc2', dataset_file='./data/yc2/yc2_annotations_trainval.json', densecap_eval_file='./tools/densevid_eval/evaluate.py', densecap_references=['./data/yc2/val_yc2.json'], dur_file='./data/yc2/yc2_duration_frame.csv', feature_root='./data/', gated_mask=False, id='yc2-2L-gt-mask-19', image_feat_size=3072, in_emb_dropout=0.1, kernel_list=[1, 3, 5, 7, 9, 11, 15, 21, 27, 33, 41, 49, 57, 71, 111, 161], learn_mask=False, max_prop_num=500, max_sentence_len=20, min_prop_before_nms=200, min_prop_num=50, n_heads=8, n_layers=2, num_workers=2, pos_thresh=0.7, sampling_sec=0.5, slide_window_size=480, slide_window_stride=20, start_from='./checkpoint/yc2-2L-gt-mask/model_epoch_19.t7', stride_factor=50, val_data_folder='validation', vis_emb_dropout=0.1)

Namespace(attn_dropout=0.2, batch_size=1, cap_dropout=0.2, cfgs_file='cfgs/yc2.yml', cuda=True, d_hidden=2048, d_model=1024, dataset='yc2', dataset_file='./data/yc2/yc2_annotations_trainval.json', densecap_eval_file='./tools/densevid_eval/evaluate.py', densecap_references=['./data/yc2/val_yc2.json'], dur_file='./data/yc2/yc2_duration_frame.csv', feature_root='./data/', gated_mask=False, id='yc2-2L-gt-mask-19', image_feat_size=3072, in_emb_dropout=0.1, kernel_list=[1, 3, 5, 7, 9, 11, 15, 21, 27, 33, 41, 49, 57, 71, 111, 161], learn_mask=False, max_prop_num=500, max_sentence_len=20, min_prop_before_nms=200, min_prop_num=50, n_heads=8, n_layers=2, num_workers=2, pos_thresh=0.7, sampling_sec=0.5, slide_window_size=480, slide_window_stride=20, start_from='./checkpoint/yc2-2L-gt-mask/model_epoch_19.t7', stride_factor=50, val_data_folder='validation', vis_emb_dropout=0.1)

loading dataset
no. of words in the vocab: 1011
no. of sentences in training: 10337, # of sentences in validation: 3492
no. of training videos: 1333
Feature root..
./data/
./data/validation
total number of samples (unique videos): 457
total number of sentences: 3492
building model
Initializing weights from ./checkpoint/yc2-2L-gt-mask/model_epoch_19.t7
/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py:1569: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
Traceback (most recent call last):
  File "test.py", line 257, in <module>
    main()
  File "test.py", line 251, in main
    recall_area = validate(model, test_loader, args)
  File "test.py", line 185, in validate
    gated_mask=args.gated_mask)
  File "/content/densecap/model/action_prop_dense_cap.py", line 412, in inference
    if np.max(segment_iou(np.array([pred_start, pred_end]), pred_results[:crt_nproposal])) > nms_thresh:
  File "/content/densecap/data/utils.py", line 48, in segment_iou
    tt1 = np.maximum(target_segment[0], candidate_segments[:, 0])
  File "/usr/local/lib/python3.6/dist-packages/torch/tensor.py", line 492, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
`

**Comment by AnukritiSinghh** [comment]
I am getting the same error as your last one. Can you please let me know how you solved this?

**Comment by pandababyer** [comment]
@abhranil08 @AnukritiSinghh  Hi, I got the same problem. I am using RTX 2080Ti so the pytorch version is 1.0 which cause the error. The solution is by restoring the data to cpu and then using numpy,  so I change pred_start and pred_end to pred_start.cpu(), pred_end.cpu() in https://github.com/salesforce/densecap/blob/45b20bb0860b0c5a5fc4878284c1ab0e6892a68f/model/action_prop_dense_cap.py#L403
and https://github.com/salesforce/densecap/blob/45b20bb0860b0c5a5fc4878284c1ab0e6892a68f/model/action_prop_dense_cap.py#L404

to                     
pred_start = pred_start.cpu()
                    pred_end = pred_end.cpu()
The problem solved.
