### ISSUE TITLE
num_samples=0 error 

### ISSUE THREAD

**Issue by AnukritiSinghh** [salesforce/densecap#43]
Can you please explain the line number 45 and 48 in train.py ? Where are these .pkl files ? Are these pre-processed files for the training data? I run the this - 
CUDA_VISIBLE_DEVICES=0 python3 scripts/train.py --dist_url='file:///mnt/data1/anukriti/videodense_dataset/densecap/nonexistent_file' --cfgs_file cfgs/anet.yml --checkpoint_path ./checkpoint/e2e-masked --world_size 1 --batch_size 1 --cuda | tee log/e2e-masked

I am getting the following error.  

` ` ` Namespace(alpha=0.95, attn_dropout=0.2, batch_size=1, beta=0.999, cap_dropout=0.2, cfgs_file='cfgs/anet.yml', checkpoint_path='./checkpoint/e2e-masked', cls_weight=1.0, cuda=True, d_hidden=2048, d_model=1024, dataset='anet', dataset_file='/mnt/data1/anukriti/videodense_dataset/data/anet/anet_annotations_trainval.json', densecap_references=['/mnt/data1/anukriti/videodense_dataset/data/anet/val_1.json', '/mnt/data1/anukriti/videodense_dataset/data/anet/val_2.json'], dist_backend='gloo', dist_url='file:///mnt/data1/anukriti/videodense_dataset/densecap/nonexistent_file', dur_file='/mnt/data1/anukriti/videodense_dataset/data/anet/anet_duration_frame.csv', enable_visdom=False, epsilon=1e-08, feature_root='/mnt/data1/anukriti/videodense_dataset/data/ActivityNet', gated_mask=False, grad_norm=1, image_feat_size=3072, in_emb_dropout=0.1, kernel_list=[1, 2, 3, 4, 5, 7, 9, 11, 15, 21, 29, 41, 57, 71, 111, 161, 211, 251], learning_rate=0.1, load_train_samplelist=False, load_valid_samplelist=False, loss_alpha_r=2, losses_log_every=1, mask_weight=0.0, max_epochs=20, max_sentence_len=20, n_heads=8, n_layers=2, neg_thresh=0.3, num_workers=1, optim='sgd', patience_epoch=1, pos_thresh=0.7, reduce_factor=0.5, reg_weight=10, sample_prob=0, sampling_sec=0.5, save_checkpoint_every=1, save_train_samplelist=False, save_valid_samplelist=False, scst_weight=0.0, seed=213, sent_weight=0.25, slide_window_size=480, slide_window_stride=20, start_from='', stride_factor=50, train_data_folder=['training'], train_sample=20, train_samplelist_path='/z/home/luozhou/subsystem/densecap_vid/train_samplelist.pkl', val_data_folder=['validation'], valid_batch_size=64, valid_samplelist_path='/z/home/luozhou/subsystem/densecap_vid/valid_samplelist.pkl', vis_emb_dropout=0.1, world_size=1)
Directory already exists.
loading dataset
 of words in the vocab: 4563
 of sentences in training: 37421, # of sentences in validation: 17505
 of training videos: 10009
Traceback (most recent call last):
  File "scripts/train.py", line 549, in <module>
    main(args)
  File "scripts/train.py", line 241, in main
    train_loader, valid_loader, text_proc, train_sampler = get_dataset(args)
  File "scripts/train.py", line 154, in get_dataset
    sample_listpath=args.train_samplelist_path,
  File "/mnt/data1/anukriti/videodense_dataset/densecap/data/anet_dataset.py", line 92, in __init__
    device=-1)  # put in memory
  File "/home/anukriti/anaconda3/envs/dense/lib/python3.6/site-packages/torchtext/data/field.py", line 356, in numericalize
    var = torch.tensor(arr, dtype=self.dtype, device=device)
RuntimeError: Device index must not be negative
` ` ` 

 And if I change device=0, I get the error ' num_samples should be a positive integer value, but got num_samples=0 ' even though I have rechecked my paths multiple times.

**Comment by AnukritiSinghh** [comment]
` Namespace(alpha=0.95, attn_dropout=0.2, batch_size=1, beta=0.999, cap_dropout=0.2, cfgs_file='cfgs/anet.yml', checkpoint_path='./checkpoint/e2e-masked', cls_weight=1.0, cuda=True, d_hidden=2048, d_model=1024, dataset='anet', dataset_file='/mnt/data1/anukriti/videodense_dataset/data/anet/anet_annotations_trainval.json', densecap_references=['/mnt/data1/anukriti/videodense_dataset/data/anet/val_1.json', '/mnt/data1/anukriti/videodense_dataset/data/anet/val_2.json'], dist_backend='gloo', dist_url='file:///mnt/data1/anukriti/videodense_dataset/densecap/nonexistent_file', dur_file='/mnt/data1/anukriti/videodense_dataset/data/anet/anet_duration_frame.csv', enable_visdom=False, epsilon=1e-08, feature_root='/mnt/data1/anukriti/videodense_dataset/data/ActivityNet', gated_mask=False, grad_norm=1, image_feat_size=3072, in_emb_dropout=0.1, kernel_list=[1, 2, 3, 4, 5, 7, 9, 11, 15, 21, 29, 41, 57, 71, 111, 161, 211, 251], learning_rate=0.1, load_train_samplelist=False, load_valid_samplelist=False, loss_alpha_r=2, losses_log_every=1, mask_weight=0.0, max_epochs=20, max_sentence_len=20, n_heads=8, n_layers=2, neg_thresh=0.3, num_workers=1, optim='sgd', patience_epoch=1, pos_thresh=0.7, reduce_factor=0.5, reg_weight=10, sample_prob=0, sampling_sec=0.5, save_checkpoint_every=1, save_train_samplelist=False, save_valid_samplelist=False, scst_weight=0.0, seed=213, sent_weight=0.25, slide_window_size=480, slide_window_stride=20, start_from='', stride_factor=50, train_data_folder=['training'], train_sample=20, train_samplelist_path='/z/home/luozhou/subsystem/densecap_vid/train_samplelist.pkl', val_data_folder=['validation'], valid_batch_size=64, valid_samplelist_path='/z/home/luozhou/subsystem/densecap_vid/valid_samplelist.pkl', vis_emb_dropout=0.1, world_size=1)
Directory already exists.
loading dataset
# of words in the vocab: 4563
# of sentences in training: 37421, # of sentences in validation: 17505
# of training videos: 10009
Traceback (most recent call last):
  File "scripts/train.py", line 549, in <module>
    main(args)
  File "scripts/train.py", line 241, in main
    train_loader, valid_loader, text_proc, train_sampler = get_dataset(args)
  File "scripts/train.py", line 154, in get_dataset
    sample_listpath=args.train_samplelist_path,
  File "/mnt/data1/anukriti/videodense_dataset/densecap/data/anet_dataset.py", line 92, in __init__
    device=-1)  # put in memory
  File "/home/anukriti/anaconda3/envs/dense/lib/python3.6/site-packages/torchtext/data/field.py", line 356, in numericalize
    var = torch.tensor(arr, dtype=self.dtype, device=device)
RuntimeError: Device index must not be negative`

**Comment by AnukritiSinghh** [comment]
Even after solving the num_samples=0 error, can you please let me know if 'Device index must not be negative ' is an error because of pytorch version being 1.6?

**Comment by AnukritiSinghh** [comment]
Changing the device index to 0 helped and then converting the torch tensors of cuda to cpu.
